### ISSUE TITLE
Should update the "How to approach these problems"

### ISSUE THREAD

**Issue by JamesEarle** [BrockCSC/crack-the-coding-interview#4]
Students in years to come will hopefully continue practicing problems from this book (maybe we should own an official CSC copy we can buy with the funds) and approaching from the right direction is a big part of actually benefiting from the exercises. Niche algorithms don't really matter, but core understanding does.

**Comment by Peter-Wilson** [comment]
Its only $40 for a copy of the book so I just ordered one for the club. We should get it in like 2 weeks.

**Comment by JamesEarle** [comment]
:+1: We should write about our interview experience with big companies, sort of a "do's and don'ts" section to the repo. Would be a good thing to have alum contribute to with experience at different companies (Google, MS, IBM, RBC, Scotiabank, etc.)

**Comment by JamesEarle** [comment]
I've added an Interview Advice directory and will be writing up a short description of each of my significant interviews, and recommend others do the same. It's currently on the `james-solutions` branch and will be merged when mine is complete.
